[project]
name = "rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "pydotenv>=0.0.7",
    "pypdf2>=3.0.1",
    "tensorflow>=2.20.0",
]
